version: "3.3"

services:
  backend:
    image: ${IMG}:${TAG}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - PYTHONPATH=/app
      - POSTGRES_USERNAME=${POSTGRES_USERNAME}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=${POSTGRES_HOST}
      - POSTGRES_PORT=${POSTGRES_PORT}
      - POSTGRES_DB_NAME=${POSTGRES_DB_NAME}
      - BUCKET_NAME=${BUCKET_NAME}
      - PORT=${PORT}
    ports:
      - "${PORT}:${PORT}"
    command: ["/bin/bash", "/opt/mlflow/run.sh"]

