apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: mlflow-gateway
  namespace: mlflow
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        name: mlflow
        number: 5000
        protocol: HTTP
      hosts:
        - "*"
