apiVersion: install.istio.io/v1alpha1
kind: IstioOperator
metadata:
  name: istio-with-extra-ports
  namespace: istio-system
spec:
  profile: default
  components:
    ingressGateways:
      - namespace: istio-system
        name: istio-ingressgateway
        enabled: true
        k8s:
          service:
            ports:
              - port: 15021
                targetPort: 30130
                name: status-port
                protocol: TCP
              - port: 80
                targetPort: 32668
                name: http2
                protocol: TCP
              - port: 443
                targetPort: 30438
                name: https
                protocol: TCP
              - port: 31400
                targetPort: 30138
                name: not-know
                protocol: TCP
              - port: 15443
                targetPort: 32203
                name: tls
                protocol: TCP
              - port: 5000
                targetPort: 5000
                name: mlflow
                protocol: TCP
              - port: 9090
                targetPort: 9090
                name: seldon-monitoring
                protocol: TCP