apiVersion: networking.istio.io/v1beta1
kind: Gateway
metadata:
  name: mlflow
spec:
  selector:
    istio: ingressgateway
  servers:
    - port:
        number: 5000
        name: mlflow
        protocol: HTTP
      hosts:
        - '*'