apiVersion: networking.istio.io/v1beta1
kind: VirtualService
metadata:
  name: my-virtualservice
spec:
  hosts:
    - '*'
  gateways:
    - mlflow
  http:
    - match:
        - port: 5000
      route:
        - destination:
            host: mlflow.local
            port:
              number: 5000